print ("How do you make an alien fall asleep?")
input ("")
print ("you rocket")
input ("")
input ("")
print ("What do you call a bear with no teeth?")
input ("")
print ("a gummy bear")
input ("")
input ("")
print ("why did the scarecrow win an award?")
input ("")
print ("because it did outstanding in its field")
input ("")
input ("")
print ("why was the broom late to work?")
input ("")
print ("it over swept")
input ("")
input ("")
print ("")