name = input("what is your name? ")
print (f"Hello {name} and welcome to my chat")
mood = input("What is your mood today?")
print(f"well,I hope you're ready for a conversation!")
topic = input ("What do you want to talk about today?")
print (f"Alright, let's talk about {topic}")
topic = input (f"What is your favorite thing about {topic}?")
topic = input (f"Anything you don't like about it?")
topic = input (f"Okay, got it. Any other topics you want to talk about?")
print (f"Sounds good. Let's talk about {topic}")
topic = input (f"What do you like about {topic}")
print (f"Now, I'm going to be asking you some questions.")
food = input (f"What is your favorite food")
print (f"Nice choice! I love {food}")
vacation = input ("What is your ideal vacation?")
print (f"Sounds great! Which friends would you bring?")
friend = input ("Nice! They would be fun to bring!")
clothes = input ("What would you pack? Any specific clothes?")
print ("Nice choices. Well, thanks for chatting with me! See you next time!")